### ISSUE TITLE
broken cmd + v on mac

### ISSUE THREAD

**Issue by zynth17** [sonnylazuardi/chatgpt-desktop#1]
steps to reproduce : 
1. install the app
2. click login
3. try to copy a text and paste the copied text to the textbox

**Comment by sonnylazuardi** [comment]
weird issue, seems working on windows will take a look for mac

**Comment by sonnylazuardi** [comment]
Tried to fix this but still have issue on production build https://github.com/tauri-apps/tauri/issues/5770
