### ISSUE TITLE
[Bug] - tauri command not found during building in Arch Linux

### ISSUE THREAD

**Issue by D3vil0p3r** [sonnylazuardi/chatgpt-desktop#14]
Hello,
I'm trying to build chatgpt-desktop by `yarn tauri build` but I get the following error:
```
yarn run v1.22.19
$ tauri build
/bin/sh: line 1: tauri: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I installed `yarn`, `tauri-devel-meta` and also Rust, and followed Tauri App docs (https://tauri.app/v1/guides/getting-started/prerequisites/) but I continue to get this error. Even if I try to use `yarn cargo-tauri build` (despite I have cargo-tauri tool), I get:
```
yarn run v1.22.19
error Command "cargo-tauri" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sonnylazuardi** [comment]
Thanks for the pull request
