### ISSUE TITLE
What is the license of this repo?

### ISSUE THREAD

**Issue by jtran** [sonnylazuardi/chatgpt-desktop#16]
I see no mention of any license anywhere in this repo.  Can you please [choose a license and add it to the repo](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)?  Thank you.

**Comment by sonnylazuardi** [comment]
Added MIT License https://github.com/sonnylazuardi/chatgpt-desktop/blob/master/LICENSE
