### ISSUE TITLE
API Mode is broken. OpenAI API returned an error: Too Many Requests. Set OpenAI API Key: click menu (top left) > OpenAI API Key > Done.

### ISSUE THREAD

**Issue by SpartanTech** [sonnylazuardi/chatgpt-desktop#45]
API Mode is broken on the current release. OpenAI Usage says the apikey hasn't even been used, brand new account, meanwhile the program says

"OpenAI API returned an error: Too Many Requests. Set [OpenAI API Key](https://platform.openai.com/account/api-keys): click menu (top left) > OpenAI API Key > Done."
![Screenshot 2023-04-04 223317](https://user-images.githubusercontent.com/3395163/229974592-12fbf22d-de5d-49b1-98d0-a6ddb0ebb82e.png)

**Comment by hansenc0705** [comment]
@SpartanTech how did you solve this issue?

**Comment by SpartanTech** [comment]
That specific error was a openai issue. Servers were busy and it threw out a general error, which this app only gives a broad error message. I had a second account though with the same exact error, but that one was billing. The free trial set up on that account expired and was out of API calls, signing up for the service fixed it.

But I don't use this app anymore, there are a lot of other issues with it in regards to the UI, the handling of session tokens, and just general overall use. The taskbar pop up can show up in random places sometimes making it unusable
